vim.cmd('set termguicolors')

vim.cmd('let g:dracula_colorterm = 1')
vim.cmd('let g:dracula_bold = 1')
vim.cmd('let g:dracula_italic = 1')
vim.cmd('let g:dracula_underline = 1')
vim.cmd('let g:dracula_undercurl = 1')
--vim.cmd('colorscheme dracula_pro_lincoln')
--vim.cmd('colorscheme dracula_pro_base')
--vim.cmd('colorscheme dracula_pro_blade')
--vim.cmd('colorscheme dracula_pro_morbius')
--vim.cmd('colorscheme dracula_pro_buffy')
--vim.cmd('colorscheme dracula_pro_van_helsing')
--vim.cmd('colorscheme dracula_pro')

--vim.cmd('let ayucolor="light"')
--vim.cmd('let ayucolor="mirage"')
--vim.cmd('let ayucolor="dark"')
--vim.cmd('colorscheme ayu')
--vim.cmd('colorscheme night-owl')
vim.cmd('colorscheme dracula')
--vim.cmd('colorscheme iceberg')
--vim.cmd('colorscheme one')
